name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: clang-format -i --verbose src/main/main.c src/libchessviz/chessviz.c src/libchessviz/chessviz.h

      - name: Build application
        run: make
